Post:
  type: entity
  table: posts
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    blog_id:
      type: integer
    user_id:
      type: integer
    title:
      length: 128
      type: string
    content:
      type: string
    created:
      type: datetime