User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
      length: 64
      unique: true
    email:
      length: 64
      type: string
    password:
      type: string
  manyToOne:
    role:
      targetEntity: Role